name = "MatrixAssembly"
uuid = "387d6434-66b3-4999-9a74-654017a16986"
authors = ["peter "]
version = "0.1.0"

[deps]
MeshStructs = "e7ff797b-5c94-4f68-b228-7c9c2c88eb4f"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Profile = "1.11.0"
ProgressBars = "1.5.1"
SparseArrays = "1.11.0"
StaticArrays = "1.9.15"
