[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
HeatInduction = "47bd84b5-b0a6-4386-94a4-5d1013581d7c"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MatrixAssembly = "387d6434-66b3-4999-9a74-654017a16986"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
