name = "HeatInduction"
uuid = "47bd84b5-b0a6-4386-94a4-5d1013581d7c"
authors = ["lupeterm <lukas.petermann13@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixAssembly = "387d6434-66b3-4999-9a74-654017a16986"
MeshStructs = "e7ff797b-5c94-4f68-b228-7c9c2c88eb4f"

[compat]
LinearAlgebra = "1.11.0"
